name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build Gateway service
        run: dotnet publish src/GatewayService/Rsoi.Lab3.GatewayService.HttpApi/Rsoi.Lab3.GatewayService.HttpApi.csproj -c Release -o Lab3Publish/GatewayService

      - name: Build Library service
        run: dotnet publish src/LibraryService/Rsoi.Lab3.LibraryService.HttpApi/Rsoi.Lab3.LibraryService.HttpApi.csproj -c Release -o Lab3Publish/LibraryService

      - name: Build Rating service
        run: dotnet publish src/RatingService/Rsoi.Lab3.RatingService.HttpApi/Rsoi.Lab3.RatingService.HttpApi.csproj -c Release -o Lab3Publish/RatingService

      - name: Build Reservation service
        run: dotnet publish src/ReservationService/Rsoi.Lab3.ReservationService.HttpApi/Rsoi.Lab3.ReservationService.HttpApi.csproj -c Release -o Lab3Publish/ReservationService

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push gateway service docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./gateway-service.Dockerfile
          tags: shaimu/ds_lab:lab3-gateway-service

      - name: Build and push library service docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./library-service.Dockerfile
          tags: shaimu/ds_lab:lab3-library-service

      - name: Build and push rating service docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./rating-service.Dockerfile
          tags: shaimu/ds_lab:lab3-rating-service

      - name: Build and push reservation service docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./reservation-service.Dockerfile
          tags: shaimu/ds_lab:lab3-reservation-service

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Stop app
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: | 
            cd lab3
            docker-compose -f docker-compose.yml down

      - name: Send docker-compose.yml file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source: "docker-compose.yml"
          target: "lab3"


      - name: Start app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: | 
            cd lab3
            docker-compose -f docker-compose.yml up -d --pull always

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating-service
          PORT_NUMBER: 8050
          USERNAME: ${{ secrets.HOST_USERNAME }}
          PASSWORD: ${{ sectets.HOST_ADDRESS }}

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 3
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
        continue-on-error: true
